security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800   # 7 jours
                path: /
                remember_me_parameter: _remember_me

    access_control:
        # Pages publiques (accessible sans connexion)
        - { path: ^/$, roles: PUBLIC_ACCESS }                    # Page d'accueil
        - { path: ^/login, roles: PUBLIC_ACCESS }                # Page de connexion
        - { path: ^/register, roles: PUBLIC_ACCESS }             # Page d'inscription
        - { path: ^/logout, roles: PUBLIC_ACCESS }               # Déconnexion
        
        # Toutes les autres pages nécessitent une connexion
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10